<?xml version="1.0" encoding="UTF-8"?>
<!-- You may freely edit this file. See commented blocks below for -->
<!-- some examples of how to customize the build. -->
<!-- (If you delete it and reopen the project it will be recreated.) -->
<!-- By default, only the Clean and Build commands use this build script. -->
<!-- Commands such as Run, Debug, and Test only use this build script if -->
<!-- the Compile on Save feature is turned off for the project. -->
<!-- You can turn off the Compile on Save (or Deploy on Save) setting -->
<!-- in the project's Project Properties dialog box.-->
<project name="BattelCity" default="default" basedir=".">
    <description>Builds, tests, and runs the project BattelCity.</description>
    <import file="nbproject/build-impl.xml"/>
    <path id="project.classpath">
        <fileset dir="lib">
            <include name="**/*.jar"/>
        </fileset>
    </path>
    <target name="test" depends="compile">
        <mkdir dir="build/test-classes"/>
        <javac srcdir="test" destdir="build/test-classes" includeantruntime="false">
            <classpath>
                <path refid="project.classpath"/>
                <pathelement path="build/classes"/>
            </classpath>
        </javac>
        <junit printsummary="true" haltonfailure="true">
            <classpath>
                <path refid="project.classpath"/>
                <pathelement path="build/classes"/>
                <pathelement path="build/test-classes"/>
            </classpath>
            <test name="test.Models.TreeTest"/>
        </junit>
    </target>
</project>
